/**
 * Client automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import axios, {AxiosRequestConfig} from "axios";
import {ClientAbstract, CredentialsInterface, TokenStoreInterface} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {PeopleTag} from "./PeopleTag";
import {FilmTag} from "./FilmTag";
import {StarshipTag} from "./StarshipTag";
import {SpeciesTag} from "./SpeciesTag";
import {VehicleTag} from "./VehicleTag";
import {PlanetTag} from "./PlanetTag";

export class Client extends ClientAbstract {
    public people(): PeopleTag
    {
        return new PeopleTag(
            this.httpClient,
            this.parser
        );
    }

    public film(): FilmTag
    {
        return new FilmTag(
            this.httpClient,
            this.parser
        );
    }

    public starship(): StarshipTag
    {
        return new StarshipTag(
            this.httpClient,
            this.parser
        );
    }

    public species(): SpeciesTag
    {
        return new SpeciesTag(
            this.httpClient,
            this.parser
        );
    }

    public vehicle(): VehicleTag
    {
        return new VehicleTag(
            this.httpClient,
            this.parser
        );
    }

    public planet(): PlanetTag
    {
        return new PlanetTag(
            this.httpClient,
            this.parser
        );
    }



    public static build(): Client
    {
        return new Client('https://swapi.dev/api', new Anonymous());
    }
}
