/**
 * Client automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import axios, {AxiosRequestConfig} from "axios";
import {ClientAbstract, CredentialsInterface, TokenStoreInterface} from "sdkgen-client"
import {OAuth2} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {PeopleTag} from "./PeopleTag";
import {FilmTag} from "./FilmTag";
import {StarshipTag} from "./StarshipTag";
import {VehicleTag} from "./VehicleTag";
import {SpecieTag} from "./SpecieTag";
import {PlanetTag} from "./PlanetTag";

export class Client extends ClientAbstract {
    public people(): PeopleTag
    {
        return new PeopleTag(
            this.httpClient,
            this.parser
        );
    }

    public film(): FilmTag
    {
        return new FilmTag(
            this.httpClient,
            this.parser
        );
    }

    public starship(): StarshipTag
    {
        return new StarshipTag(
            this.httpClient,
            this.parser
        );
    }

    public vehicle(): VehicleTag
    {
        return new VehicleTag(
            this.httpClient,
            this.parser
        );
    }

    public specie(): SpecieTag
    {
        return new SpecieTag(
            this.httpClient,
            this.parser
        );
    }

    public planet(): PlanetTag
    {
        return new PlanetTag(
            this.httpClient,
            this.parser
        );
    }



    public static build(clientId: string, clientSecret: string, tokenStore: TokenStoreInterface|null, scopes: Array<string>|null): Client
    {
        return new Client('https://swapi.dev/api', new OAuth2(clientId, clientSecret, 'https://api.typehub.cloud/authorization/token', '', tokenStore, scopes));
    }
}
