/**
 * Collection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface Collection {
    count?: number
    next?: string
    previous?: string
}
