/**
 * FilmCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Collection} from "./Collection";
import {Film} from "./Film";

export interface FilmCollection extends Collection {
    results?: Array<Film>
}

