/**
 * Film automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * A Film is a single film.
 */
export interface Film {
    title?: string
    episode_id?: number
    opening_crawl?: string
    director?: string
    producer?: string
    release_date?: string
    species?: Array<string>
    starships?: Array<string>
    vehicles?: Array<string>
    characters?: Array<string>
    planets?: Array<string>
    url?: string
    created?: string
    edited?: string
}
