/**
 * PeopleCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Collection} from "./Collection";
import {People} from "./People";

export interface PeopleCollection extends Collection {
    results?: Array<People>
}

