/**
 * People automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * A People is an individual person or character within the Star Wars universe
 */
export interface People {
    name?: string
    birth_year?: string
    eye_color?: string
    gender?: string
    hair_color?: string
    height?: string
    mass?: string
    skin_color?: string
    homeworld?: string
    films?: Array<string>
    species?: Array<string>
    starships?: Array<string>
    vehicles?: Array<string>
    url?: string
    created?: string
    edited?: string
}
