/**
 * PeopleTag automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TagAbstract, HttpRequest} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {People} from "./People";
import {PeopleCollection} from "./PeopleCollection";

export class PeopleTag extends TagAbstract {
    /**
     * Get all the people
     *
     * @returns {Promise<PeopleCollection>}
     * @throws {ClientException}
     */
    public async getAll(search?: string): Promise<PeopleCollection> {
        const url = this.parser.url('/people', {
        });

        let request: HttpRequest = {
            url: url,
            method: 'GET',
            headers: {
            },
            params: this.parser.query({
                'search': search,
            }, [
            ]),
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as PeopleCollection;
        }

        const statusCode = response.status;
        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }
    /**
     * Get a specific people
     *
     * @returns {Promise<People>}
     * @throws {ClientException}
     */
    public async get(id: string): Promise<People> {
        const url = this.parser.url('/people/:id', {
            'id': id,
        });

        let request: HttpRequest = {
            url: url,
            method: 'GET',
            headers: {
            },
            params: this.parser.query({
            }, [
            ]),
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as People;
        }

        const statusCode = response.status;
        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }



}
