/**
 * PlanetTag automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TagAbstract, HttpRequest} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {Planet} from "./Planet";
import {PlanetCollection} from "./PlanetCollection";

export class PlanetTag extends TagAbstract {
    /**
     * Get all the planets
     *
     * @returns {Promise<PlanetCollection>}
     * @throws {ClientException}
     */
    public async getAll(search?: string): Promise<PlanetCollection> {
        const url = this.parser.url('/planets', {
        });

        let request: HttpRequest = {
            url: url,
            method: 'GET',
            headers: {
            },
            params: this.parser.query({
                'search': search,
            }, [
            ]),
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as PlanetCollection;
        }

        const statusCode = response.status;
        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }
    /**
     * Get a specific planet
     *
     * @returns {Promise<Planet>}
     * @throws {ClientException}
     */
    public async get(id: string): Promise<Planet> {
        const url = this.parser.url('/planets/:id', {
            'id': id,
        });

        let request: HttpRequest = {
            url: url,
            method: 'GET',
            headers: {
            },
            params: this.parser.query({
            }, [
            ]),
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as Planet;
        }

        const statusCode = response.status;
        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }



}
