/**
 * PlanetCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Collection} from "./Collection";
import {Planet} from "./Planet";
export interface PlanetCollection extends Collection {
    results?: Array<Planet>
}
