/**
 * Planet automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * A Planet is a large mass, planet or planetoid in the Star Wars Universe, at the time of 0 ABY
 */
export interface Planet {
    name?: string
    diameter?: string
    rotation_period?: string
    orbital_period?: string
    gravity?: string
    population?: string
    climate?: string
    terrain?: string
    surface_water?: string
    residents?: Array<string>
    films?: Array<string>
    url?: string
    created?: string
    edited?: string
}
