/**
 * Root automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface Root {
    films?: string
    people?: string
    planets?: string
    species?: string
    starships?: string
    vehicles?: string
}

