/**
 * Specie automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * A Species resource is a type of person or character within the Star Wars Universe.
 */
export interface Specie {
    name?: string
    classification?: string
    designation?: string
    average_height?: string
    average_lifespan?: string
    eye_colors?: string
    hair_colors?: string
    skin_colors?: string
    language?: string
    homeworld?: string
    people?: Array<string>
    films?: Array<string>
    url?: string
    created?: string
    edited?: string
}
