/**
 * SpecieCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Collection} from "./Collection";
import {Specie} from "./Specie";
export interface SpecieCollection extends Collection {
    results?: Array<Specie>
}
