/**
 * SpeciesCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Collection} from "./Collection";
import {Species} from "./Species";
export interface SpeciesCollection extends Collection {
    results?: Array<Species>
}
