/**
 * Starship automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * A Starship is a single transport craft that has hyperdrive capability.
 */
export interface Starship {
    name?: string
    model?: string
    starship_class?: string
    manufacturer?: string
    cost_in_credits?: string
    length?: string
    crew?: string
    passengers?: string
    max_atmosphering_speed?: string
    hyperdrive_rating?: string
    MGLT?: string
    cargo_capacity?: string
    consumables?: string
    films?: Array<string>
    pilots?: Array<string>
    url?: string
    created?: string
    edited?: string
}
