/**
 * StarshipCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Collection} from "./Collection";
import {Starship} from "./Starship";
export interface StarshipCollection extends Collection {
    results?: Array<Starship>
}
