/**
 * Vehicle automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * A Vehicle is a single transport craft that does not have hyperdrive capability
 */
export interface Vehicle {
    name?: string
    model?: string
    vehicle_class?: string
    manufacturer?: string
    length?: string
    cost_in_credits?: string
    crew?: string
    passengers?: string
    max_atmosphering_speed?: string
    cargo_capacity?: string
    consumables?: string
    films?: Array<string>
    pilots?: Array<string>
    url?: string
    created?: string
    edited?: string
}

