/**
 * VehicleCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Collection} from "./Collection";
import {Vehicle} from "./Vehicle";
export interface VehicleCollection extends Collection {
    results?: Array<Vehicle>
}
