/**
 * VehicleTag automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TagAbstract, HttpRequest} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {Vehicle} from "./Vehicle";
import {VehicleCollection} from "./VehicleCollection";

export class VehicleTag extends TagAbstract {
    /**
     * Get all the vehicles
     *
     * @returns {Promise<VehicleCollection>}
     * @throws {ClientException}
     */
    public async getAll(search?: string): Promise<VehicleCollection> {
        const url = this.parser.url('/vehicles', {
        });

        let request: HttpRequest = {
            url: url,
            method: 'GET',
            headers: {
            },
            params: this.parser.query({
                'search': search,
            }, [
            ]),
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as VehicleCollection;
        }

        const statusCode = response.status;
        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }
    /**
     * Get a specific vehicle
     *
     * @returns {Promise<Vehicle>}
     * @throws {ClientException}
     */
    public async get(id: string): Promise<Vehicle> {
        const url = this.parser.url('/vehicles/:id', {
            'id': id,
        });

        let request: HttpRequest = {
            url: url,
            method: 'GET',
            headers: {
            },
            params: this.parser.query({
            }, [
            ]),
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as Vehicle;
        }

        const statusCode = response.status;
        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }



}
